### ISSUE TITLE
Uncaught TypeError: r is not a function

### ISSUE THREAD

**Issue by sean-clayton** [gdpelican/retort#19]
After enabling retort, as a user, they click on an emoji in the retort emoji picker. There is a console log per emoji click, which is as follows:

`Uncaught TypeError: r is not a function`

**Comment by gdpelican** [comment]
Thanks for the report! I've pushed a fix to the latest master. ☀️

**Comment by sean-clayton** [comment]
Thanks for the _super_ quick fix! Great plugin, by the way :smile:
