### ISSUE TITLE
Retort emojis are preselected for post emojis

### ISSUE THREAD

**Issue by frictionel** [gdpelican/retort#20]
After activating the retort plugin the retort-emojis are preselected in every posts emoji-popup.

![screen shot 2016-07-30 at 01 10 19](https://cloud.githubusercontent.com/assets/10785122/17270023/a86f7f22-5658-11e6-94bf-d8ac220ba267.png)

**Comment by gdpelican** [comment]
I believe this is fixed with Discourse's new emoji picker
