### ISSUE TITLE
Icon popup not appearing

### ISSUE THREAD

**Issue by shadowbrush** [gdpelican/retort#23]
Hi,

I just installed this plugin for an up-to-date Discourse installation. It was working nicely until I tried to limit the icon selection. I tried to set it to this:

    slight_smile|smile|sunglasses|dizzyface|stuc_out_tongue|dizzy_face|upside_down|+1|-1|clap|wave|ok_hand|raised_hand|heart|rage

There's probably an invalid icon in the list. After saving this setting, the icon popup would not appear anymore. Neither when clicking on the retort button, nor on the emoji button in the post editor. The page would be dimmed, but no popup shown. Resetting the plugin's settings to default didn't help. Neither did disabling the plug-in, nor rebuilding the container. 

The inspector reports this error: `Uncaught TypeError: Cannot read property 'icons' of undefined`, which apparently happens in a `render` method (last line in the (uglified code below):

    function render(page, offset, options) {
      keyValueStore.set({ key: "emojiPage", value: page });
      keyValueStore.set({ key: "emojiOffset", value: offset });

      var toolbarItems = toolbar(page);
      var rows = [];
      var row = [];
      var icons = groups[page].icons;

Any idea now to fix it?

**Comment by gdpelican** [comment]
Hrm, I'm not able to reproduce this; adding the aforementioned value into the custom retort field yields this for me:

![screen shot 2017-01-15 at 12 57 36 am](https://cloud.githubusercontent.com/assets/750477/21954696/a2f6bba2-dabd-11e6-83dd-179574f0a3cf.png)

..which is about what I'd expect. Are you able to tell what the value of 'groups' and 'page' are there?

**Comment by shadowbrush** [comment]
@gdpelican Thanks for the fast response! It turned out to be client-side caching. After resetting it, the popup appears with the correct icons. Oh, and thank you for providing this plug-in!
