### ISSUE TITLE
Can't see the button

### ISSUE THREAD

**Issue by inY2K** [gdpelican/retort#27]
Hey there, I've installed the plugin, however, the button/emoji are not appearing below the topics. Is there any additional step i need to take of is it not working with the latest Discourse version?

The plugin is activated!

**Comment by daath** [comment]
My forum has lost the retort-button as well...

**Comment by daath** [comment]
I see the button now, but it doesn't seem to work any longer...

**Comment by jbcpollak** [comment]
Same problem. I guess something changed in discourse and broke the plug-in.

**Comment by schungx** [comment]
You sure you're on the latest version?  I think this is fixed.

**Comment by jbcpollak** [comment]
I assume so, over the weekend I put the GitHub url in like it says in the readme and ran the rebuild command. The url didn't have a branch or revision spec, so it should be up to date.
