### ISSUE TITLE
Change the background font to match the used theme

### ISSUE THREAD

**Issue by IwishIcanFLighT** [gdpelican/retort#35]
Hi !

We use a dark theme on our Discourse instance and the reaction background color doesn't match our theme. 
![](https://puu.sh/zG2EU/c6073799df.png)
While I could fork the project and edit the color as I see fit, it would be great that this background color could match the user theme or to at least have an option to change it.

Thanks !

**Comment by gdpelican** [comment]
Cool, thanks, I can grab this when I get some spare time. In the meantime though, you can edit the background color by adding some custom CSS to your theme by clicking 'Edit CSS/HTML' under `admin/customize/themes`, and adding something like
```
.post-retort {
  color: white;
  background: black;
}
```

**Comment by IwishIcanFLighT** [comment]
Thanks you very much! This fix worked like a charm!

Looking forward to the update! :wink:

**Comment by gdpelican** [comment]
This has been fixed for a while now, there should be no troubles with using Retort with a theme. �
