### ISSUE TITLE
Icons After Selection Showing as Undefined

### ISSUE THREAD

**Issue by iamstrained** [gdpelican/retort#41]
After an upgrade to HTTPS and a migration to a new URL, our Retort icon selector still pops up and shows the externally pulled icon set. However it fails to populate the selected image into the icon line. (As shown).

![image](https://user-images.githubusercontent.com/4333299/51356059-2da1db00-1a87-11e9-8e9f-7689e415d6ca.png)

Not sure if I'm missing a configuration step or if this is something with the conversion to HTTPS from HTTP where the plug-in doesn't like the conversion? Ideas welcome to try to resolve. Have done the usual remapping and rebake of posts, but that didn't matter for this plugin as it's not 'baking' in the Discourse sense likely.

**Comment by gdpelican** [comment]
@angusmcleod Any ideas about this one? I'll take a look at it over the weekend as well.

**Comment by gdpelican** [comment]
Hey @angusmcleod I've reverted the standard_retort_count change for now; we can take a look into why it might be causing this over the next wee while before re-merging it :)

**Comment by iamstrained** [comment]
I do see some log errors in the JS that may or may not be related to this. 

![image](https://user-images.githubusercontent.com/4333299/51432874-1c82d680-1c0d-11e9-9bbf-6105e2e398ee.png)

**Comment by iamstrained** [comment]
I did an app rebuild and re-cloned the directory (master) and now it's loading the images. But it's breaking the template up oddly (seems it's not inheriting the main style/area)?

![image](https://user-images.githubusercontent.com/4333299/51712981-85e45a00-1ffe-11e9-9217-8badd36dc11e.png)
