### ISSUE TITLE
Better integration on Neutral theme

### ISSUE THREAD

**Issue by alfonsomunozpomer** [gdpelican/retort#48]
I’ve [forked the repo and tweaked it](https://github.com/alfonsomunozpomer/retort/commit/b4221408b4362ed6834cfe3d60e57fdd5a79546c) to improve colours with the neutral theme. I have very little knowledge of how Discourse themes work, so I’m not sure if removing the properties will integrate well with other themes. I can make a PR if you want to review it.

Before:
![image](https://user-images.githubusercontent.com/4425744/64115456-9c6a4500-cd87-11e9-9453-2c13707b75d0.png)

After:
![image](https://user-images.githubusercontent.com/4425744/64115508-bb68d700-cd87-11e9-9370-c74c6655d7fe.png)

**Comment by GokulNC** [comment]
@alfonsomunozpomer Please make this PR.. This is something really required.
Without this, the retorts look odd.

**Comment by aaronpk** [comment]
I would go one step further and remove the border even! IMO these should match the default buttons exactly.
