### ISSUE TITLE
After discourse update reaction modal showing white blank

### ISSUE THREAD

**Issue by TheBaby5** [gdpelican/retort#52]
https://i.gyazo.com/c5b8f8601b070f7c2a905bd80c3f86c3.mp4

Please check the above video capture, after discourse update retort stopped working, when I try to click on emoji icon the popup modal is showing white blank as shown in the video & the below image.

![image](https://user-images.githubusercontent.com/44883516/79369522-b8b19f80-7f6e-11ea-905f-dac4e3feaa87.png)

**Comment by hifihedgehog** [comment]
Yes, Retort is no longer working with the latest version of Discourse. I just get a blank window now.

**Comment by slambert** [comment]
I'm seeing this also, on the current release.

**Comment by slambert** [comment]
I just updated another discourse install and got the same result. Did some quick troubleshooting to see if it was the recent CSS change in the last commit that made the difference, but it looks like the div for the emoji picker is empty for some reason.

**Comment by gdpelican** [comment]
Thanks for the updates; I'm working on this today and will have a fix out
by end of day. :D

**Comment by gdpelican** [comment]
This one should now be fixed 👍

**Comment by theblazehen** [comment]
Having issues with the "recently used" emojis, is it a me problem or anyone else affected?

**Comment by hifihedgehog** [comment]
Custom emojis that were working just a week ago in retort no longer are working. Please fix.
