### ISSUE TITLE
Picker Is Not Shown Anymore

### ISSUE THREAD

**Issue by p0fi** [gdpelican/retort#62]
After the recent updates the picker is not shown anymore when clicking on the emoji symbol on our discourse. Can somebody confirm this issue?

**Comment by gdpelican** [comment]
Could you link to the site in question? Are there any errors in the console, CSS / HTML customizations, or other plugins that may be interfering? Which version of Discourse are you running?

**Comment by p0fi** [comment]
Oh sure! It’s https://community.hom.ee
Currently running Discourse 2.4.2 (7cc7baf378)

I can’t spot any errors in the console. I also checked the custom styling and removed it completely - didn’t change the situation. Before updating recently it all worked fine. We didn’t change any configuration (css or plugins) since then.

**Comment by gdpelican** [comment]
Hmm the latest fixes are for the beta branch (currently 2.5.0.beta3). Discourse unfortunately doesn't offer an easy way that I know of to version plugin releases to particular branches of the app, meaning there are discrepencies between versions at times. If you're able to upgrade to the beta branch for a time, I'd recommend that, or alternatively waiting until 2.5.x hits the stable branch.

Sorry for not offering a more helpful solution!

**Comment by p0fi** [comment]
So with 2.5.0 it should work again? 🤔

**Comment by gdpelican** [comment]
Yep; I can confirm it's working on the demo site (https://discourse-babble.com), which is running 2.5.0:

![Captura de pantalla 2020-05-01 a la(s) 10 44 04 p  m](https://user-images.githubusercontent.com/750477/80800351-5fe43700-8bfd-11ea-9917-39f19377855b.png)

**Comment by GokulNC** [comment]
@p0fi It works perfect for me. I'm on `Discourse 2.5.0.beta3`

**Comment by frictionel** [comment]
Same problem here with v2.4.5

**Comment by p0fi** [comment]
Can confirm that the issue does not exist anymore on discourse > 2.5.0 🤙🏼
