### ISSUE TITLE
Reaction count is not visible clearly due to white background

### ISSUE THREAD

**Issue by TheBaby5** [gdpelican/retort#63]
Due to full white background the number of likes are not visible, also after giving reaction it takes time to reflect or we have to refresh the page to see if it reacted or not.... 

Check the heart reaction, it reacted 3 times, but the number of times, is not clearly visible.

![image](https://user-images.githubusercontent.com/44883516/80790273-0a336e80-8bac-11ea-95a5-91a31379fe91.png)

**Comment by gdpelican** [comment]
Looks like there may be some custom styling involved here. Have you tried putting something like
```
span.post-retort__count {
  color: black;
}
```

into your custom css under Customize -> Themes -> Edit CSS/HTML?

**Comment by TheBaby5** [comment]
Nope, its still the same, I did cloudflare clear cache everything, even tried to browse as guest with login. 

Added the line

![image](https://user-images.githubusercontent.com/44883516/80802825-1af4dc00-8bce-11ea-8e03-bf0609ff6676.png)

Still the same! 

![image](https://user-images.githubusercontent.com/44883516/80802779-fbf64a00-8bcd-11ea-9905-f939e4fb6ba7.png)

**Comment by TheBaby5** [comment]
It worked, thank you! 👯‍♀️ 

![image](https://user-images.githubusercontent.com/44883516/80802992-935b9d00-8bce-11ea-97dd-028ff74fa063.png)

**Comment by TheBaby5** [comment]
Also after giving reaction it takes time to reflect or we have to refresh the page to see if it reacted or not....

**Comment by GokulNC** [comment]
@gdpelican I think the color [here](https://github.com/gdpelican/retort/blob/af40ec2a324b04d555cedf9276d6c4e1fbdbe411/assets/stylesheets/retort.scss#L52) should be `$primary` instead of `$secondary`, since by default, Discourse uses `$primary` for all text colors I guess.
