### ISSUE TITLE
Does not work with 2.5.0.beta4

### ISSUE THREAD

**Issue by aaronpk** [gdpelican/retort#64]
I upgraded from 2.5.0.beta2 to 2.5.0.beta4 today and this plugin caused the entire forum to break due to a JS error in this plugin.

The error in the console is unfortunately not very helpful:

```
_ember_jquery-3a388c5a0562670ed1eea762f12e041d92b4a418316d3f9f83e793d3ba6be5d7.js:4060 jQuery.Deferred exception: Cannot read property 'find' of undefined TypeError: Cannot read property 'find' of undefined
    at t.postFor (https://forum.ohmydollar.com/assets/plugins/retort-2b5f24e04afd560bb80ec54c5a13ff2bb05edb69aa06e7aa11af1be8275a56c0.js:1:1494)
```

I have to disable this plugin for now until this is fixed.

**Comment by gdpelican** [comment]
👋 Looks like you may have a funky topic somewhere which doesn't have a postStream set properly.

Try updating to the latest version of retort, which should account for this possibility :)

**Comment by aaronpk** [comment]
Is there a way to upgrade this plugin specifically? I just ran the regular `./launcher rebuild app` which upgraded Discourse itself, and I assume would also grab the latest from this plugin.

**Comment by gdpelican** [comment]
That'll do it to upgrade everything, or you can try visiting `https://<your
instance>/admin/upgrade` to upgrade specific plugins / discourse itself.

**Comment by aaronpk** [comment]
hm okay, that's what I ran and when it came back online I was getting this error
