### ISSUE TITLE
Retort plugin is conflicting after discourse new update

### ISSUE THREAD

**Issue by TheBaby5** [gdpelican/retort#65]
After the new discourse update, retort is conflicting with custom header links, please have a look.

After disabling retort other plugin is working fine, this happened after the new update from discourse.

Here is the full conversation with the other developer.

https://meta.discourse.org/t/custom-header-links/90588/87?u=thebaby5

Discourse Current Version Installed.

![image](https://user-images.githubusercontent.com/44883516/83338173-3cd1a380-a2df-11ea-9978-8676886c0289.png)

**Comment by hhyyrylainen** [comment]
I also get problems after updating discourse related to retort.
https://meta.discourse.org/t/2-5-0-beta5-breaks-javascript-plugins-in-themes/153378/4?u=boost
contains a stack trace

**Comment by hhyyrylainen** [comment]
Using latest commit from master, this is now fixed for me.
