### ISSUE TITLE
Emoji-button - No on-click reaction (Widget not showing)

### ISSUE THREAD

**Issue by exetico** [gdpelican/retort#70]
Hi,

Our reaction button got broken after the latest update. By clicking it, nothing happens. No JS-errors is thrown in the console, by clicking it. I can't really tell what's going on.

We're on the latest build, with all plugins updated, too.

![image](https://user-images.githubusercontent.com/3549445/91316621-52a91480-e7b9-11ea-8a90-0aa1d30b9cd6.png)

**Comment by Johannestegner** [comment]
Having the same issue. Seeing nothing have changed in this repository since a while back, I would guess something changed in Discourse.
If I find any way around it I'll post here :)

**Comment by forgenst** [comment]
Yep, I think the latest update may have broken it.

**Comment by Johannestegner** [comment]
> 
> 
> Yep, I think the latest update may have broken it.

There is a patch which allows it to show, but there are quite a few changes to the internal emoji selector code, so it's not working as good as before. A lot better than nothing at all, but could use some well deserved CSS magic from someone who have a good eye to that stuff! :)

**Comment by angusmcleod** [comment]
This is now fixed: https://github.com/gdpelican/retort/commit/272fe4c643864a9a419248abc2fd2e81258d3478
