### ISSUE TITLE
Uncaught Error: Could not find module `@popperjs/core`

### ISSUE THREAD

**Issue by DoomDesign** [gdpelican/retort#75]
**Expected behaviour:** 
The reaction picker should be shown under each post.

**Actual behaviour:**
The retort picker is not visible in any post and a console error is thrown instead.

We recently updated our forum to 2.5.1 stable, then installed the retort plugin for the very first time.
The plugin seems to by installed correctly, I can access its settings and everything.
But inside threads, there is no reaction picker.

This JS error is thrown in the console:
![2020-09-09_15-01-16](https://user-images.githubusercontent.com/466316/92601905-ac2b3c00-f2ad-11ea-884a-09c2d9c55d55.png)

**Comment by angusmcleod** [comment]
@DoomDesign Thank you for this. Turned out to be an incorrect filename 🤯. Now resolved.

Also, I've set up a public staging server running ``stable`` that includes this plugin (partly as a result of this issue). See: https://stable.try.thepavilion.io/

**Comment by DoomDesign** [comment]
Thank you, it is working now!

**Comment by cfstras** [comment]
Just did a rebuild of our Forum... 
Retort is at 95fa9d8, but we still get this error in the console and no retorts:
 
![grafik](https://user-images.githubusercontent.com/1156864/94548503-1ef65a00-0251-11eb-8802-5602a257664a.png)

**Comment by cfstras** [comment]
Just verified: The filename got corrected, but the issue seems to persist.
I noticed there is no entry for 2.5.2, only for 2.5.1. Can I assume adding that version should fix it?

**Comment by cfstras** [comment]
Fixed it: (running on our forum and working)
https://github.com/gdpelican/retort/pull/77

**Comment by dtraleigh** [comment]
Hi all. I'm seeing this exact same thing on stable 2.5.4. I'm happy to test and add compat for it here but can you help? What is the key that was added to the  .discourse-compatibility file? I'd like to test on my install before opening a PR.
